# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(leenium-cmd-terminal-cwd)" zsh -l
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(leenium-cmd-terminal-cwd)" zsh -lc "tmux attach || tmux new -s Work"
bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, E, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(leenium-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, leenium-launch-browser
bindd = SUPER SHIFT, B, Browser (private), exec, leenium-launch-browser --private
bindd = SUPER, C, VScode, exec, uwsm-app -- code
bindd = SUPER SHIFT, M, Music, exec, leenium-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, leenium-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, leenium-launch-tui lazydocker
bindd = SUPER SHIFT, T, Telegram, exec, leenium-launch-or-focus ^org\\.telegram\\.desktop$ "uwsm-app -- Telegram"
bindd = SUPER SHIFT, G, Signal, exec, leenium-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, I, Discord, exec, leenium-launch-or-focus ^discord$ "uwsm-app -- discord"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden-desktop

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER, A, ChatGPT, exec, leenium-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Grok, exec, leenium-launch-webapp "https://grok.com"
bindd = SUPER, M, Email, exec, leenium-launch-or-focus ^thunderbird$ "uwsm-app -- thunderbird"
bindd = SUPER SHIFT, Y, YouTube, exec, leenium-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, leenium-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, leenium-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, leenium-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, leenium-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, leenium-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Leenium Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Leenium menu, exec, leenium-menu

# Logitech MX Keys
# bind = SUPER SHIFT, S, exec, leenium-cmd-screenshot          # Print Screen Button
# bind = SUPER, H, exec, voxtype record toggle                 # Dictation Button
# bind = SUPER, PERIOD, exec, leenium-launch-walker -m symbols # Emoji Button