accent = "#35d6a0"
cursor = "#d8f7ea"
foreground = "#d8f7ea"
background = "#060b0f"
selection_foreground = "#060b0f"
selection_background = "#94f1cd"

color0 = "#0b1319"
color1 = "#ff5f56"
color2 = "#35d6a0"
color3 = "#ffd479"
color4 = "#376781"
color5 = "#8cb7a9"
color6 = "#94f1cd"
color7 = "#d8f7ea"
color8 = "#1d313d"
color9 = "#ff7a72"
color10 = "#5cf0ad"
color11 = "#ffe19a"
color12 = "#4a6d82"
color13 = "#a7d3c2"
color14 = "#b7f7de"
color15 = "#d8f7ea"
