return {
  base46_theme = "leenium",
  plugin = {
    dir = vim.fn.stdpath "config",
    name = "leenium",
    priority = 1000,
  },
  apply = function()
    local colors = {
      bg = "#060b0f",
      panel = "#0b1319",
      line = "#1d313d",
      line_strong = "#376781",
      fg = "#d8f7ea",
      muted = "#8cb7a9",
      accent = "#35d6a0",
      accent_bright = "#5cf0ad",
      sea = "#94f1cd",
      sea_bright = "#b7f7de",
      soft = "#a7d3c2",
      warn = "#ffd479",
      warn_bright = "#ffe19a",
      error = "#ff5f56",
      error_soft = "#ff7a72",
      blue = "#4a6d82",
    }

    local set = vim.api.nvim_set_hl

    vim.o.termguicolors = true
    vim.g.colors_name = "leenium"

    local groups = {
      Normal = { fg = colors.fg, bg = colors.bg },
      NormalNC = { fg = colors.fg, bg = colors.bg },
      NormalFloat = { fg = colors.fg, bg = colors.panel },
      FloatBorder = { fg = colors.line, bg = colors.panel },
      FloatTitle = { fg = colors.accent, bg = colors.panel, bold = true },
      Cursor = { fg = colors.bg, bg = colors.fg },
      CursorLine = { bg = colors.panel },
      CursorLineNr = { fg = colors.fg, bold = true },
      LineNr = { fg = colors.muted },
      SignColumn = { bg = colors.bg },
      EndOfBuffer = { fg = colors.bg, bg = colors.bg },
      ColorColumn = { bg = colors.panel },
      Conceal = { fg = colors.muted },
      Visual = { bg = colors.line },
      Search = { fg = colors.bg, bg = colors.warn },
      IncSearch = { fg = colors.bg, bg = colors.accent },
      CurSearch = { fg = colors.bg, bg = colors.accent_bright },
      MatchParen = { fg = colors.accent, bg = colors.line, bold = true },
      Pmenu = { fg = colors.fg, bg = colors.panel },
      PmenuSel = { fg = colors.bg, bg = colors.accent },
      PmenuSbar = { bg = colors.line },
      PmenuThumb = { bg = colors.line_strong },
      StatusLine = { fg = colors.fg, bg = colors.panel },
      StatusLineNC = { fg = colors.muted, bg = colors.panel },
      WinSeparator = { fg = colors.line },
      VertSplit = { fg = colors.line },
      TabLine = { fg = colors.muted, bg = colors.panel },
      TabLineSel = { fg = colors.fg, bg = colors.bg, bold = true },
      TabLineFill = { bg = colors.panel },
      Folded = { fg = colors.soft, bg = colors.panel },
      FoldColumn = { fg = colors.muted, bg = colors.bg },
      Directory = { fg = colors.accent },
      Title = { fg = colors.accent, bold = true },
      Question = { fg = colors.accent },
      MoreMsg = { fg = colors.accent },
      WarningMsg = { fg = colors.warn },
      ErrorMsg = { fg = colors.error, bold = true },
      ModeMsg = { fg = colors.sea },
      NonText = { fg = colors.line },
      Whitespace = { fg = colors.line },
      SpecialKey = { fg = colors.line_strong },

      Comment = { fg = colors.muted, italic = true },
      Constant = { fg = colors.warn },
      String = { fg = colors.sea },
      Character = { fg = colors.sea },
      Number = { fg = colors.warn },
      Boolean = { fg = colors.warn },
      Float = { fg = colors.warn },
      Identifier = { fg = colors.soft },
      Function = { fg = colors.fg },
      Statement = { fg = colors.accent },
      Conditional = { fg = colors.accent },
      Repeat = { fg = colors.accent },
      Label = { fg = colors.accent },
      Operator = { fg = colors.soft },
      Keyword = { fg = colors.accent },
      Exception = { fg = colors.error_soft },
      PreProc = { fg = colors.accent_bright },
      Include = { fg = colors.accent_bright },
      Define = { fg = colors.accent_bright },
      Macro = { fg = colors.accent_bright },
      PreCondit = { fg = colors.accent_bright },
      Type = { fg = colors.soft },
      StorageClass = { fg = colors.accent },
      Structure = { fg = colors.soft },
      Typedef = { fg = colors.soft },
      Special = { fg = colors.sea },
      SpecialComment = { fg = colors.soft },
      Underlined = { fg = colors.sea, underline = true },
      Todo = { fg = colors.bg, bg = colors.warn, bold = true },
      Error = { fg = colors.error },

      DiagnosticError = { fg = colors.error },
      DiagnosticWarn = { fg = colors.warn },
      DiagnosticInfo = { fg = colors.sea },
      DiagnosticHint = { fg = colors.soft },
      DiagnosticOk = { fg = colors.accent_bright },
      DiagnosticUnderlineError = { undercurl = true, sp = colors.error },
      DiagnosticUnderlineWarn = { undercurl = true, sp = colors.warn },
      DiagnosticUnderlineInfo = { undercurl = true, sp = colors.sea },
      DiagnosticUnderlineHint = { undercurl = true, sp = colors.soft },

      GitSignsAdd = { fg = colors.accent },
      GitSignsChange = { fg = colors.warn },
      GitSignsDelete = { fg = colors.error },

      DiffAdd = { fg = colors.accent_bright, bg = colors.panel },
      DiffChange = { fg = colors.warn, bg = colors.panel },
      DiffDelete = { fg = colors.error, bg = colors.panel },
      DiffText = { fg = colors.fg, bg = colors.line },

      TelescopeNormal = { fg = colors.fg, bg = colors.panel },
      TelescopeBorder = { fg = colors.line, bg = colors.panel },
      TelescopePromptNormal = { fg = colors.fg, bg = colors.panel },
      TelescopePromptBorder = { fg = colors.line_strong, bg = colors.panel },
      TelescopePromptPrefix = { fg = colors.accent },
      TelescopeSelection = { fg = colors.fg, bg = colors.line },
      TelescopeMatching = { fg = colors.accent_bright, bold = true },

      LazyNormal = { fg = colors.fg, bg = colors.bg },
      LazyButton = { fg = colors.fg, bg = colors.panel },
      LazyButtonActive = { fg = colors.bg, bg = colors.accent },
      LazyH1 = { fg = colors.bg, bg = colors.accent, bold = true },
      LazySpecial = { fg = colors.sea },

      NvimTreeNormal = { fg = colors.fg, bg = colors.bg },
      NvimTreeWinSeparator = { fg = colors.line, bg = colors.bg },
      NvimTreeRootFolder = { fg = colors.accent, bold = true },
      NvimTreeFolderName = { fg = colors.soft },
      NvimTreeOpenedFolderName = { fg = colors.sea },
      NvimTreeEmptyFolderName = { fg = colors.muted },

      ["@comment"] = { fg = colors.muted, italic = true },
      ["@keyword"] = { fg = colors.accent },
      ["@keyword.function"] = { fg = colors.accent },
      ["@string"] = { fg = colors.sea },
      ["@number"] = { fg = colors.warn },
      ["@type"] = { fg = colors.soft },
      ["@type.builtin"] = { fg = colors.sea_bright },
      ["@function"] = { fg = colors.fg },
      ["@function.builtin"] = { fg = colors.sea_bright },
      ["@variable"] = { fg = colors.soft },
      ["@variable.builtin"] = { fg = colors.warn_bright },
      ["@property"] = { fg = colors.soft },
      ["@operator"] = { fg = colors.soft },
      ["@punctuation"] = { fg = colors.muted },
    }

    for group, opts in pairs(groups) do
      set(0, group, opts)
    end
  end,
}
