### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: Leenium Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 060b0f
backdrop: 060b0f

# Terminal colors (Leenium Terminal palette)
term_palette: 0b1319;ff5f56;35d6a0;ffd479;376781;8cb7a9;94f1cd;d8f7ea
term_palette_bright: 1d313d;ff7a72;5cf0ad;ffe19a;4a6d82;a7d3c2;b7f7de;d8f7ea

# Text colors
term_foreground: d8f7ea
term_foreground_bright: d8f7ea
term_background_bright: 0b1319
