# Menus
bindd = SUPER, SPACE, Launch apps, exec, leenium-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, leenium-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, leenium-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, leenium-menu toggle
bindd = SUPER ALT, SPACE, Leenium menu, exec, leenium-menu
bindd = SUPER, ESCAPE, System menu, exec, leenium-menu system
bindld = , XF86PowerOff, Power menu, exec, leenium-menu system
bindd = SUPER, K, Show key bindings, exec, leenium-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, leenium-toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, leenium-menu background
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, leenium-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, leenium-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, leenium-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, leenium-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, leenium-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, leenium-toggle-nightlight

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, leenium-brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, leenium-brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, leenium-brightness-display-apple +60000

# Captures
bindd = , PRINT, Screenshot, exec, leenium-cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, leenium-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, leenium-menu share

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(leenium-battery-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, leenium-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, leenium-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, leenium-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, leenium-launch-tui btop
bindd = SHIFT CTRL, ESCAPE, Activity, exec, leenium-launch-tui btop
bindd = CTRL ALT, DELETE, Activity, exec, leenium-launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
# bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
# bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Zoom toggle / in / out
bind = SUPER, Z, exec, leenium-screen-magnifier toggle
bind = SUPER, Kp_Add, exec, leenium-screen-magnifier in
bind = SUPER, Kp_Subtract, exec, leenium-screen-magnifier out
# bind = SUPER, equal, exec, leenium-screen-magnifier in
# bind = SUPER, minus, exec, leenium-screen-magnifier out

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, leenium-lock-screen
